services:
  # Backend Web Service
  - type: web
    name: kitkuhar-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: kitkuhar-db
          property: connectionString
    
  # Frontend Web Service (serving static files)
  - type: web
    name: kitkuhar-frontend
    env: node
    buildCommand: cd frontend && npm ci && npm run build
    startCommand: cd frontend && npx serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: REACT_APP_API_URL
        value: https://kitkuhar-backend.onrender.com

databases:
  - name: kitkuhar-db
    databaseName: kitkuhar
    user: kitkuhar_user
    plan: free